"""add_currency_and_space_id

Revision ID: 0a07ce537992
Revises: c6c756ea8aaf
Create Date: 2025-11-29 23:22:42.439841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a07ce537992'
down_revision: Union[str, None] = 'c6c756ea8aaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('load_items', sa.Column('space_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'load_items', 'spaces', ['space_id'], ['id'])
    op.add_column('trips', sa.Column('currency', sa.String(length=3), nullable=False, server_default='USD'))
    op.add_column('trips', sa.Column('exchange_rate', sa.Numeric(precision=10, scale=4), nullable=False, server_default='1.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'exchange_rate')
    op.drop_column('trips', 'currency')
    op.drop_constraint(None, 'load_items', type_='foreignkey')
    op.drop_column('load_items', 'space_id')
    # ### end Alembic commands ###
