"""add_trip_fields

Revision ID: 55c17e9701b8
Revises: 948a6b43aabd
Create Date: 2025-11-29 23:57:52.902132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55c17e9701b8'
down_revision: Union[str, None] = '948a6b43aabd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    pickup_cost_type = sa.Enum('flat_rate', 'per_pallet', name='pickup_cost_type')
    pickup_cost_type.create(op.get_bind(), checkfirst=True)
    op.add_column('trips', sa.Column('pickup_cost_type', pickup_cost_type, nullable=False, server_default='flat_rate'))
    op.add_column('trips', sa.Column('bond_cost', sa.Numeric(precision=10, scale=2), nullable=False, server_default='500.00'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'bond_cost')
    op.drop_column('trips', 'pickup_cost_type')
    sa.Enum(name='pickup_cost_type').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_label_prices_dimensions'), table_name='label_prices')
    op.drop_table('label_prices')
    # ### end Alembic commands ###
