"""replace_labeling_fields_with_json

Revision ID: 6ac27759fe35
Revises: e72718a775a6
Create Date: 2025-11-29 07:18:19.220208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ac27759fe35'
down_revision: Union[str, None] = 'e72718a775a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('labeling_details', sa.JSON(), nullable=True))
    op.drop_constraint('reservations_label_file_id_fkey', 'reservations', type_='foreignkey')
    op.drop_column('reservations', 'labeling_required')
    op.drop_column('reservations', 'label_file_id')
    op.drop_column('reservations', 'label_quantity')
    op.drop_column('reservations', 'label_dimensions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('label_dimensions', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('reservations', sa.Column('label_quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reservations', sa.Column('label_file_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('reservations', sa.Column('labeling_required', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_foreign_key('reservations_label_file_id_fkey', 'reservations', 'client_documents', ['label_file_id'], ['id'])
    op.drop_column('reservations', 'labeling_details')
    # ### end Alembic commands ###
