"""create_label_prices_table

Revision ID: 948a6b43aabd
Revises: 0a07ce537992
Create Date: 2025-11-29 23:51:55.570470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '948a6b43aabd'
down_revision: Union[str, None] = '0a07ce537992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_label_prices_dimensions', table_name='label_prices')
    op.drop_table('label_prices')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label_prices',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('dimensions', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='label_prices_pkey')
    )
    op.create_index('ix_label_prices_dimensions', 'label_prices', ['dimensions'], unique=True)
    # ### end Alembic commands ###
