"""add_reservation_enhancements

Revision ID: c4aa29bf41ee
Revises: 0001_initial
Create Date: 2025-11-29 06:31:23.719373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4aa29bf41ee'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('load_items', 'total_weight',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.add_column('reservations', sa.Column('invoice_data_id', sa.UUID(), nullable=True))
    op.alter_column('reservations', 'pickup_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_foreign_key(None, 'reservations', 'client_documents', ['invoice_data_id'], ['id'])
    op.drop_column('reservations', 'cargo_description')
    op.drop_column('reservations', 'cargo_type')
    op.drop_column('reservations', 'cargo_weight')
    op.alter_column('users', 'billing_address',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'billing_address',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('reservations', sa.Column('cargo_weight', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('reservations', sa.Column('cargo_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('reservations', sa.Column('cargo_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.alter_column('reservations', 'pickup_details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('reservations', 'invoice_data_id')
    op.alter_column('load_items', 'total_weight',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
