"""add_pickup_cost_to_trips

Revision ID: c6c756ea8aaf
Revises: 6ac27759fe35
Create Date: 2025-11-29 23:19:38.711249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6c756ea8aaf'
down_revision: Union[str, None] = '6ac27759fe35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('pickup_cost', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'pickup_cost')
    # ### end Alembic commands ###
