"""add_international_column

Revision ID: e72718a775a6
Revises: c4aa29bf41ee
Create Date: 2025-11-29 07:09:41.658060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e72718a775a6'
down_revision: Union[str, None] = 'c4aa29bf41ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('labeling_required', sa.Boolean(), nullable=True))
    op.add_column('reservations', sa.Column('label_quantity', sa.Integer(), nullable=True))
    op.add_column('reservations', sa.Column('label_dimensions', sa.String(length=50), nullable=True))
    op.add_column('reservations', sa.Column('label_file_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'reservations', 'client_documents', ['label_file_id'], ['id'])
    op.add_column('trips', sa.Column('is_international', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'is_international')
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.drop_column('reservations', 'label_file_id')
    op.drop_column('reservations', 'label_dimensions')
    op.drop_column('reservations', 'label_quantity')
    op.drop_column('reservations', 'labeling_required')
    # ### end Alembic commands ###
