"""add_verification_fields_retry_6

Revision ID: ed3a935383e4
Revises: 95d196bacbce
Create Date: 2025-12-02 20:29:39.591951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed3a935383e4'
down_revision: Union[str, None] = '95d196bacbce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('notifications') - Skipped
    # op.drop_table('fleet_vehicles') - Skipped
    # op.drop_table('fleet_drivers') - Skipped
    op.add_column('users', sa.Column('verification_status', sa.Enum('pending_documents', 'pending_review', 'verified', 'rejected', name='verification_status'), server_default='pending_documents', nullable=False))
    op.add_column('users', sa.Column('ine_front_file_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('ine_back_file_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('ine_selfie_file_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('verification_notes', sa.String(), nullable=True))
    op.add_column('users', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('verified_by', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('rejection_reason', sa.String(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_verification_status'), 'users', ['verification_status'], unique=False)
    op.create_foreign_key(None, 'users', 'client_documents', ['ine_back_file_id'], ['id'])
    op.create_foreign_key(None, 'users', 'client_documents', ['ine_selfie_file_id'], ['id'])
    op.create_foreign_key(None, 'users', 'client_documents', ['ine_front_file_id'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['verified_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_verification_status'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'rejection_reason')
    op.drop_column('users', 'verified_by')
    op.drop_column('users', 'verified_at')
    op.drop_column('users', 'verification_notes')
    op.drop_column('users', 'ine_selfie_file_id')
    op.drop_column('users', 'ine_back_file_id')
    op.drop_column('users', 'ine_front_file_id')
    op.drop_column('users', 'verification_status')
    op.drop_column('users', 'verification_status')
    # ### end Alembic commands ###
